services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  bank.auth.api:
    image: bank.auth.api
    build:
      context: .
      dockerfile: src/Bank.Auth.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db